// ============================================================
// js/firebase.js  – Firebase Init & Auth
// ============================================================
// SETUP: Replace the firebaseConfig object below with your own
// project credentials from https://console.firebase.google.com
// ============================================================

import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
import {
  getAuth,
  GoogleAuthProvider,
  signInWithPopup,
  signInAnonymously,
  signOut,
  onAuthStateChanged,
  linkWithPopup
} from "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js";
import {
  getFirestore,
  doc, collection,
  setDoc, addDoc, getDoc, getDocs,
  updateDoc, deleteDoc,
  query, where, orderBy, limit, onSnapshot,
  serverTimestamp
} from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";

// ─── YOUR FIREBASE CONFIG ───────────────────────────────────
// Real credentials live in js/firebase-config.js — a file that is never
// regenerated by future code updates, so your keys survive redeploys.
import { firebaseConfig, isFirebaseConfigured } from "./firebase-config.js?v=20260705a";

if (!isFirebaseConfigured()) {
  // Surface a loud, visible warning instead of silently failing to save data.
  window.addEventListener("DOMContentLoaded", () => {
    const banner = document.createElement("div");
    banner.style.cssText = "position:fixed;top:0;left:0;right:0;z-index:99999;background:#c0392b;color:#fff;padding:10px 16px;font:600 13px/1.4 sans-serif;text-align:center;";
    banner.textContent = "⚠ Firebase isn't configured yet — edit js/firebase-config.js with your project keys, or your data won't save.";
    document.body.prepend(banner);
  });
}

const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
export const db   = getFirestore(app);
export const googleProvider = new GoogleAuthProvider();

// Auth helpers
export const loginWithGoogle = () => signInWithPopup(auth, googleProvider);
export const loginAnonymously = () => signInAnonymously(auth);
export const logout = () => signOut(auth);
export const onAuth = (cb) => onAuthStateChanged(auth, cb);

// Upgrade an anonymous session to a permanent Google account.
// Keeps the SAME uid, so all Firestore data under /users/{uid}/... is preserved automatically.
export const linkAnonymousToGoogle = () => linkWithPopup(auth.currentUser, googleProvider);

// Sign out then immediately reopen the Google account picker — lets someone
// who logged in with the wrong email switch to the correct one.
export const switchGoogleAccount = async () => {
  await signOut(auth);
  googleProvider.setCustomParameters({ prompt: "select_account" });
  return signInWithPopup(auth, googleProvider);
};

// Firestore helpers
export {
  doc, collection,
  setDoc, addDoc, getDoc, getDocs,
  updateDoc, deleteDoc,
  query, where, orderBy, limit, onSnapshot,
  serverTimestamp
};

// ─── Firestore path helpers ──────────────────────────────────
// All user data lives under /users/{uid}/...
export const userCol = (uid, col) => collection(db, "users", uid, col);
export const userDoc = (uid, col, id) => doc(db, "users", uid, col, id);
export const profileDoc = (uid) => doc(db, "users", uid, "profile", "data");
